plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-slate

title: "APCSA"
description: "AP Computer Science A"

url                      : https://BillJr99.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/APCSA" # the subpath of your site, e.g. "/blog"

# Reading Files
include:
  - .htaccess
  - _pages
  - files